# Generated by Django 5.2.5 on 2025-08-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["status", "-created_at"]},
        ),
        migrations.AlterField(
            model_name="task",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.BooleanField(
                choices=[(True, "Done"), (False, "Not done")], default=False
            ),
        ),
    ]
