# Generated by Django 5.2.5 on 2025-08-10 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_tag_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="name",
        ),
    ]
