# Generated by Django 5.2.5 on 2025-08-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_task_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="content",
            field=models.TextField(),
        ),
    ]
